[build]
  functions = "functions"
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/constant-contact/*"
  to = "/.netlify/functions/constant-contact/:splat"
  status = 200

# SEO-friendly redirects for subject pages
[[redirects]]
  from = "/mathematics"
  to = "/?subject=mathematics"
  status = 200

[[redirects]]
  from = "/physics"
  to = "/?subject=physics"
  status = 200

[[redirects]]
  from = "/chemistry"
  to = "/?subject=chemistry"
  status = 200

[[redirects]]
  from = "/programming"
  to = "/?subject=programming"
  status = 200

[[redirects]]
  from = "/blog"
  to = "/?view=blog"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20.10.0"

# Headers for SEO and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"

# Environment variables should be set in Netlify UI under:
# Site settings > Build & deploy > Environment variables
#
# Required variables:
# CONSTANT_CONTACT_API_KEY=your_api_key_here
# CONSTANT_CONTACT_ACCESS_TOKEN=your_access_token_here
# CONSTANT_CONTACT_CLIENT_ID=your_client_id_here
# CONSTANT_CONTACT_CLIENT_SECRET=your_client_secret_here