[build]
  functions = "functions"
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/constant-contact/*"
  to = "/.netlify/functions/constant-contact/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20.10.0"

# Environment variables should be set in Netlify UI under:
# Site settings > Build & deploy > Environment variables
#
# Required variables:
# CONSTANT_CONTACT_API_KEY=your_api_key_here
# CONSTANT_CONTACT_ACCESS_TOKEN=your_access_token_here
# CONSTANT_CONTACT_CLIENT_ID=your_client_id_here
# CONSTANT_CONTACT_CLIENT_SECRET=your_client_secret_here